import React from 'react';
import { 
  FiSearch, FiFileText, FiImage, FiBriefcase, FiTrendingUp, FiPenTool, FiEdit3, FiMap, FiStar
} from 'react-icons/fi';

export const seoSteps = [
  {
    id: 'meta',
    number: 1,
    icon: <FiSearch />,
    title: 'عنوان ووصف الموقع (Meta Tags)',
    urgency: 'عالية',
    urgencyColor: 'bg-red-100 text-red-700',
    time: '5 دقائق',
    dashboardPath: '/dashboard/settings',
    dashboardLabel: 'إعدادات الـ SEO',
    why: 'العنوان والوصف هم أول شيء بيشوفه أي حد في نتائج جوجل. لو مش مظبوطين، الناس مش هتضغط على موقعك حتى لو ظاهر في النتائج.',
    steps: [
      'ادخل على "إعدادات الـ SEO" من القايمة الجانبية',
      'في تاب "الإعدادات العامة"، هتلاقي حقل "عنوان الموقع العام (Meta Title)"',
      'اكتب عنوان جذاب فيه الكلمة المفتاحية الأساسية — مثال: "المتحدة لخدمات النظافة | تنظيف واجهات وفلل ومصانع في مصر"',
      'في حقل "وصف الموقع العام (Meta Description)" اكتب وصف 150-160 حرف فيه أهم الخدمات والميزات',
      'اضغط "حفظ التعديلات"',
    ],
    tips: [
      'العنوان لازم يكون 50-60 حرف كحد أقصى',
      'الوصف لازم يكون 150-160 حرف — اكتب فيه عرض مغري',
      'حط الكلمة المفتاحية الأساسية في أول العنوان',
      'متكررش نفس الكلمات — جوجل بيعاقب على ده',
    ],
    example: {
      title: 'المتحدة لخدمات النظافة | تنظيف واجهات وفلل وقصور ومصانع',
      desc: 'شركة المتحدة لخدمات النظافة والتعقيم — خبرة +10 سنوات في تنظيف الواجهات الزجاجية والحجرية، الفلل، القصور، المصانع والمستشفيات. احجز الآن!',
    },
  },
  {
    id: 'headings',
    number: 2,
    icon: <FiFileText />,
    title: 'عناوين الصفحات (H1 & H2)',
    urgency: 'عالية',
    urgencyColor: 'bg-red-100 text-red-700',
    time: '10 دقائق',
    dashboardPath: '/dashboard/settings',
    dashboardLabel: 'إعدادات الـ SEO → تاب الصفحات',
    why: 'الـ H1 و H2 هم العناوين اللي جوجل بيفهم منها محتوى كل صفحة. لو فاضيين أو مش مكتوبين صح، جوجل مش هيعرف يصنّف صفحاتك.',
    steps: [
      'ادخل على "إعدادات الـ SEO" من القايمة الجانبية',
      'اضغط على تاب "إعدادات الصفحات (H1/H2/Meta)"',
      'هتلاقي كل صفحات الموقع (الرئيسية، الخدمات، العملاء، الفروع، من نحن، تواصل معنا، الحجز)',
      'اضغط على كل صفحة واملأ الحقول:',
      '• H1 = العنوان الرئيسي — لازم يحتوي على الكلمة المفتاحية الأهم',
      '• H2 = العنوان الفرعي — وصف مختصر يوضح أكتر',
      '• Meta Title = العنوان في نتائج جوجل لهذه الصفحة تحديداً',
      '• Meta Description = الوصف في نتائج جوجل لهذه الصفحة',
      'اضغط "حفظ التعديلات"',
    ],
    tips: [
      'كل صفحة لازم يكون ليها H1 مختلف ومميز',
      'حط الكلمة المفتاحية في أول الـ H1',
      'صفحة "الخدمات" مثلاً: H1 = "خدمات النظافة والتعقيم في مصر"',
      'صفحة "الرئيسية": H1 = "أفضل شركة نظافة في مصر — المتحدة"',
    ],
    example: {
      title: 'صفحة الخدمات → H1: خدمات النظافة والتعقيم الاحترافية في مصر',
      desc: 'H2: نقدم أكثر من 16 خدمة متخصصة بأحدث المعدات وفريق مدرب',
    },
  },
  {
    id: 'ogimage',
    number: 3,
    icon: <FiImage />,
    title: 'صورة المشاركة (Open Graph)',
    urgency: 'متوسطة',
    urgencyColor: 'bg-amber-100 text-amber-700',
    time: '3 دقائق',
    dashboardPath: '/dashboard/settings',
    dashboardLabel: 'إعدادات الـ SEO → الهوية البصرية',
    why: 'لما حد يشارك لينك الموقع على فيسبوك أو واتساب، لازم تظهر صورة جذابة. لو مفيش صورة، الشيرة هتبان فارغة ومحدش هيضغط عليها.',
    steps: [
      'ادخل على "إعدادات الـ SEO"',
      'في قسم "الهوية البصرية" هتلاقي "Open Graph Image"',
      'ارفع صورة بمقاس 1200×630 بيكسل — فيها اسم الشركة واللوجو ورقم التواصل',
      'كمان ارفع الـ Favicon (أيقونة المتصفح) — هتظهر في تاب المتصفح',
    ],
    tips: [
      'المقاس المثالي: 1200×630 بيكسل',
      'الصورة لازم تكون واضحة ومعبرة عن البراند',
      'اختبر الصورة — شارك اللينك على واتساب وشوف شكلها',
      'حط رقم الواتساب على الصورة للتسهيل',
    ],
    example: null,
  },
  {
    id: 'schema',
    number: 4,
    icon: <FiBriefcase />,
    title: 'بيانات الشركة (Schema — JSON-LD)',
    urgency: 'متوسطة',
    urgencyColor: 'bg-amber-100 text-amber-700',
    time: '5 دقائق',
    dashboardPath: '/dashboard/settings',
    dashboardLabel: 'إعدادات الـ SEO → المتقدمة',
    why: 'الـ Schema بيساعد جوجل يعرف إن ده موقع شركة وليه بيانات محددة (اسم، عنوان، لوجو، سوشيال ميديا). ده بيحسن ظهورك في نتائج البحث.',
    steps: [
      'ادخل على "إعدادات الـ SEO"',
      'افتح قسم "إعدادات الـ SEO المتقدمة" (في آخر الصفحة)',
      'في حقل "Organization Schema" ألصق الكود ده (غيّر البيانات ببيانات شركتك):',
    ],
    tips: [
      'الكود لازم يكون JSON صحيح — لو في غلطة ممكن جوجل يتجاهله',
      'حط كل لينكات السوشيال ميديا في الـ sameAs',
      'حط لينك اللوجو الرسمي في الـ logo',
    ],
    example: {
      title: 'Organization Schema',
      desc: `{
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "المتحدة لخدمات النظافة",
  "url": "https://almotaheda.com",
  "logo": "https://almotaheda.com/logo.png",
  "contactPoint": { "@type": "ContactPoint", "telephone": "+201234567890" },
  "sameAs": ["https://facebook.com/almotaheda", "https://instagram.com/almotaheda"]
}`,
    },
  },
  {
    id: 'pixels',
    number: 5,
    icon: <FiTrendingUp />,
    title: 'ربط البيكسل وأكواد التتبع',
    urgency: 'عالية',
    urgencyColor: 'bg-red-100 text-red-700',
    time: '5 دقائق',
    dashboardPath: '/dashboard/tracking',
    dashboardLabel: 'التتبع (Pixels)',
    why: 'بدون البيكسل، مش هتعرف تقيس أداء الإعلانات ومش هتعرف مين اللي جاي من الحملات. الداتا = قرارات أحسن = نتائج أقوى.',
    steps: [
      'ادخل على "التتبع (Pixels)" من القايمة الجانبية',
      'في كل منصة (فيسبوك، جوجل، تيك توك، سناب شات) حط الـ Pixel ID بتاعك',
      'الأكواد هتتحقن تلقائياً في كل صفحات الموقع',
      'لو عندك كود تتبع مخصص (مثلاً: Chatbot أو Hotjar)، ألصقه في "حقن أكواد مخصصة"',
      'اضغط "حفظ"',
    ],
    tips: [
      'فيسبوك: ادخل Events Manager → هتلاقي الـ Pixel ID (رقم طويل)',
      'Google Analytics: ادخل Admin → Data Streams → الـ ID يبدأ بـ G-',
      'GTM: ادخل tagmanager.google.com → الـ Container ID يبدأ بـ GTM-',
      'تيك توك: ادخل TikTok Ads Manager → Assets → Events',
      'نصيحة: فعّل GTM + Meta Pixel على الأقل كبداية',
    ],
    example: null,
  },
  {
    id: 'brand',
    number: 6,
    icon: <FiPenTool />,
    title: 'الهوية البصرية وبيانات الشركة',
    urgency: 'متوسطة',
    urgencyColor: 'bg-amber-100 text-amber-700',
    time: '10 دقائق',
    dashboardPath: '/dashboard/brand',
    dashboardLabel: 'الهوية البصرية',
    why: 'الهوية البصرية الموحدة بتعزز الثقة عند العملاء وبتخلي الموقع يبان احترافي. كمان بيانات الشركة (تليفون، عنوان، إيميل) مهمة للـ SEO المحلي.',
    steps: [
      'ادخل على "الهوية البصرية" — ارفع اللوجو واضبط الألوان',
      'ادخل على "البيانات المؤسسية" — اكتب اسم الشركة، التليفون، العنوان، والإيميل',
      'في قسم السوشيال ميديا — أضف لينكات كل الصفحات',
      'اكتب نبذة عن الشركة في "من نحن" — دي بتظهر في الفوتر وصفحة من نحن',
    ],
    tips: [
      'حط رقم الواتساب في "إعدادات النظام" → "إعدادات التواصل"',
      'حط لينك خريطة جوجل لكل فرع في "إدارة الفروع"',
      'اسم الشركة بالعربي والإنجليزي مهم للـ SEO',
    ],
    example: null,
  },
  {
    id: 'content',
    number: 7,
    icon: <FiEdit3 />,
    title: 'المحتوى والصفحات',
    urgency: 'عالية',
    urgencyColor: 'bg-red-100 text-red-700',
    time: '30 دقيقة',
    dashboardPath: '/dashboard/services',
    dashboardLabel: 'إدارة الخدمات',
    why: 'المحتوى هو الملك! كل خدمة لازم يكون ليها وصف تفصيلي فيه كلمات مفتاحية. جوجل بيحب المحتوى الغني والمفيد.',
    steps: [
      'ادخل على "إدارة الخدمات" — اتأكد إن كل خدمة ليها:',
      '• اسم واضح (عربي + إنجليزي)',
      '• وصف تفصيلي — على الأقل 100 كلمة — فيه كلمات مفتاحية',
      '• صورة عالية الجودة',
      '• فيديو (لو متاح) — الفيديو بيزود وقت البقاء على الصفحة',
      'ادخل على "أهم العملاء" — أضف كل العملاء بالصور والوصف',
      'ادخل على "إدارة الفروع" — أضف كل فرع بالعنوان والتليفون وخريطة جوجل',
    ],
    tips: [
      'الصور لازم تكون واضحة واحترافية — ده بيأثر على ثقة العميل',
      'الفيديو بيزود معدل التحويل 80% على الأقل',
      'في وصف كل خدمة، استخدم الكلمات اللي الناس بتبحث بيها',
      'مثال: "تنظيف واجهات زجاجية" بدل "خدمات النظافة"',
    ],
    example: null,
  },
  {
    id: 'sitemap',
    number: 8,
    icon: <FiMap />,
    title: 'ملف Sitemap و Robots',
    urgency: 'عالية',
    urgencyColor: 'bg-red-100 text-red-700',
    time: '5 دقائق',
    dashboardPath: null,
    dashboardLabel: 'تلقائي',
    why: 'الـ Sitemap بيقول لجوجل إيه كل الصفحات الموجودة في موقعك عشان يؤرشفها. بدونه جوجل ممكن يفوّت صفحات مهمة.',
    steps: [
      'الـ Sitemap بيتولّد تلقائياً — مش محتاج تعمل حاجة!',
      'الملف موجود على: yourdomain.com/sitemap.xml',
      'الـ robots.txt موجود على: yourdomain.com/robots.txt',
      'بس لازم تسجّل الـ Sitemap في Google Search Console:',
      'ادخل على search.google.com/search-console',
      'أضف الموقع → اختر "Domain" → اثبت الملكية',
      'ادخل على Sitemaps ← ألصق لينك الـ sitemap.xml',
      'اضغط Submit',
    ],
    tips: [
      'حط الدومين بتاعك في ملف .env في `NEXT_PUBLIC_SITE_URL`',
      'Google Search Console مجاني وأهم أداة لمتابعة الأرشفة',
      'بعد التسجيل، استنى 2-7 أيام لحد ما جوجل يبدأ يؤرشف',
    ],
    example: null,
  },
];

export const checklist = [
  { label: 'Meta Title العام مكتوب صح', link: 'meta', icon: <FiSearch /> },
  { label: 'Meta Description العام مكتوب', link: 'meta', icon: <FiSearch /> },
  { label: 'H1 لكل صفحة من الصفحات السبع', link: 'headings', icon: <FiFileText /> },
  { label: 'H2 لكل صفحة', link: 'headings', icon: <FiFileText /> },
  { label: 'Meta Title لكل صفحة', link: 'headings', icon: <FiFileText /> },
  { label: 'صورة Open Graph مرفوعة', link: 'ogimage', icon: <FiImage /> },
  { label: 'Favicon مرفوع', link: 'ogimage', icon: <FiImage /> },
  { label: 'Organization Schema مكتوب', link: 'schema', icon: <FiBriefcase /> },
  { label: 'Meta Pixel متربط', link: 'pixels', icon: <FiTrendingUp /> },
  { label: 'Google Analytics متربط', link: 'pixels', icon: <FiTrendingUp /> },
  { label: 'Google Tag Manager متربط', link: 'pixels', icon: <FiTrendingUp /> },
  { label: 'وصف تفصيلي لكل خدمة', link: 'content', icon: <FiEdit3 /> },
  { label: 'صور لكل خدمة', link: 'content', icon: <FiEdit3 /> },
  { label: 'بيانات كل فرع كاملة', link: 'content', icon: <FiEdit3 /> },
  { label: 'Sitemap مسجّل في Google Search Console', link: 'sitemap', icon: <FiMap /> },
];
